name: "CI CD Android"
on:
  push:
    branches:
      - "main"
      - "dev"
  pull_request:
    branches:
      - "main"
      - "dev"

  workflow_dispatch:

jobs:
  unit_test:
    name: Run Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"
          cache: "gradle"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: setup local.properties
        env:
          API_KEY: ${{secrets.API_KEY}}
        run:
          echo API_KEY="$API_KEY" > ./local.properties

      - name: Run Test
        run: |
          ./gradlew test --stacktrace

  android_test:
    name: Run Instrumentation Test
    runs-on: macos-latest
    env:
      API_KEY: ${{secrets.API_KEY}}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"
          cache: "gradle"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: setup local.properties
        env:
          API_KEY: ${{secrets.API_KEY}}
        run:
          echo API_KEY="$API_KEY" > ./local.properties

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

  build:
    runs-on: ubuntu-latest
    needs: [ unit_test, android_test ]
    env:
      API_KEY: ${{secrets.API_KEY}}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"
          cache: "gradle"

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: setup local.properties
        env:
          API_KEY: ${{secrets.API_KEY}}
        run:
          echo API_KEY="$API_KEY" > ./local.properties

      - name: Build APK
        run: ./gradlew build

      - name: Cache Build
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Release app
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: app/build/outputs/apk/debug/app-debug.apk
